// AUTO-GENERATED by asma-mfw-esmloader (renderWidgetTypes). Do not edit — regenerate.
import type { Props as W0 } from './UserListWidget'

declare global {
    interface AsmaWidgetRegistry {
        "fixture-app": {
            "user-list": W0
        }
    }
}

export {}
