/**
 * Codegen for the {@link AsmaWidgetRegistry} augmentation — turns an app's widget map into the source of
 * a `widgets.generated.d.ts` that REFERENCES each widget's declared `Props` (never copies them), so the
 * widget component stays the single source of truth. Consequences that fall out for free at the app's
 * next `tsc`:
 *   - a renamed/removed widget FILE, or a widget missing its `Props` export, breaks the generated
 *     `import type` LOUDLY (regenerate / fix the export);
 *   - a renamed widget NAME turns every stale `<EsmWidgetHost component_path="…">` into a compile error.
 *
 * Pure — returns a string; the caller writes it (`writeFileSync(out, renderWidgetTypes(...))`), so this
 * module needs no node/fs dependency. Typically invoked from the app's widget build with the SAME
 * `widgets.config` map vite already consumes, i.e. there is no second source of truth for widget names.
 *
 * @see _docs/frontend/plans/2026-07-02-15-40-plan-shell-dual-loader-esm-and-qiankun.md — REQ-002
 */

export interface WidgetTypesInput {
    /** Registry key = the microapp_name passed as `<EsmWidgetHost app>` (and the `window.__ASMA_PLATFORM__` key). */
    app: string
    /**
     * `component_path` (the widgets.json key a caller passes) → module specifier of that widget's entry,
     * RELATIVE TO the generated file, each exporting a `Props` type. This is the app's `widgets.config`
     * entries map verbatim — the single source of truth the widget build already uses.
     */
    widgets: Record<string, string>
    /** Name of the exported props type in each entry module. Default `'Props'`. */
    propsExport?: string
}

const HEADER = '// AUTO-GENERATED by asma-mfw-esmloader (renderWidgetTypes). Do not edit — regenerate.'

/**
 * Render the `widgets.generated.d.ts` source for one app. Deterministic: widgets are sorted by name so
 * regeneration produces a stable diff.
 */
export function renderWidgetTypes({ app, widgets, propsExport = 'Props' }: WidgetTypesInput): string {
    const sorted = Object.entries(widgets).sort(([a], [b]) => a.localeCompare(b))
    if (sorted.length === 0) {
        throw new Error(`renderWidgetTypes: app '${app}' has no widgets`)
    }
    const imports = sorted.map(([, spec], i) => `import type { ${propsExport} as W${i} } from '${spec}'`)
    const members = sorted.map(([name], i) => `            ${JSON.stringify(name)}: W${i}`)
    return `${[
        HEADER,
        ...imports,
        '',
        'declare global {',
        '    interface AsmaWidgetRegistry {',
        `        ${JSON.stringify(app)}: {`,
        ...members,
        '        }',
        '    }',
        '}',
        '',
        'export {}',
    ].join('\n')}\n`
}
